# Configuration file for netlify 
# Build 
[build]
functions = "netlify/functions"
publish = "./"

[build.environment]
NODE_VERSION = "18"

# Backend stuff
[[redirects]]
from = "/api/contact"
to = "/.netlify/functions/contact-discord"
status = 200

[[redirects]]
from = "/api/join"
to = "/.netlify/functions/joinus-discord"
status = 200

[[redirects]]
from = "/api/deploy"
to = "/.netlify/functions/deploy-discord"
status = 200

[[redirects]]
from = "/api/deletion/request"
to = "/.netlify/functions/deletion-request"
status = 200

[[redirects]]
from = "/api/deletion/confirm"
to = "/.netlify/functions/deletion-confirm"
status = 200

# Frontend stuff
[[redirects]]
from = "/about"
to = "/about.html"
status = 200

[[redirects]]
from = "/contact"
to = "/contact.html"
status = 200

[[redirects]]
from = "/join-us"
to = "/join-us.html"
status = 200

[[redirects]]
from = "/our-team"
to = "/join-us.html"
status = 200

[[redirects]]
from = "/locations"
to = "/features-overview"
status = 302

[[redirects]]
from = "/event-suggestions"
to = "/features-overview"
status = 302

[[redirects]]
from = "/availability-sharing"
to = "/features-overview"
status = 302

[[redirects]]
from = "/in-app-chat"
to = "/features-overview"
status = 302

[[redirects]]
from = "/features-overview"
to = "/features-overview.html"
status = 200

[[redirects]]
from = "/delete-account"
to = "/delete-account.html"
status = 200

[[redirects]]
from = "/delete-data"
to = "/delete-data.html"
status = 200

[[redirects]]
from = "/delete-account/confirm"
to = "/delete-account-confirm.html"
status = 200

[[redirects]]
from = "/delete-data/confirm"
to = "/delete-data-confirm.html"
status = 200

[[redirects]]
from = "/privacy-policy"
to = "/privacy-policy.html"
status = 200

[[redirects]]
from = "/terms-of-service"
to = "/terms-of-service.html"
status = 200

[[redirects]]
from = "/child-safety-standards"
to = "/child-safety-standards.html"
status = 200

[[redirects]]
from = "/"
to = "/index.html"
status = 200
