# Configuration file for netlify 
# Backend stuff
[build]
functions = "netlify/functions"

[[redirects]]
from = "/api/contact"
to = "/.netlify/functions/contact-discord"
status = 200

[[redirects]]
from = "/api/join"
to = "/.netlify/functions/joinus-discord"
status = 200


# Frontend stuff
[[redirects]]
from = "/about"
to = "/about.html"
status = 200

[[redirects]]
from = "/contact"
to = "/contact.html"
status = 200

[[redirects]]
from = "/join-us"
to = "/join-us.html"
status = 200

[[redirects]]
from = "/"
to = "/index.html"
status = 200
